require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'Rakefile'
    - 'config/**/*'
    - 'config.ru'
    - 'Gemfile'
    - 'bin/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'vendor/**/*'
  UseCache: false
  TargetRailsVersion: 5.2.6
  TargetRubyVersion: 2.5.1

Style/Documentation:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']